kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: container-using-read-write-root-filesystems
spec:
  policyName: Container using read-write root filesystems
  description: Alert on deployments with containers with read-write root filesystem
  rationale: Containers running with read-write root filesystem represent greater
    post-exploitation risk by allowing an attacker to modify important files in the
    container.
  remediation: Use a read-only root filesystem, and use volume mounts to allow writes
    to specific sub-directories depending on your application's needs.
  categories:
  - Docker CIS
  - Privileges
  - Cassi
  disabled: false
  lifecycleStages:
  - DEPLOY
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: ''
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: ^kube.*|^openshift.*|^redhat.*|^istio.*|^rhacs-operator.*|^stackrox.*
        label: null
    image: null
    expiration: null
  severity: MEDIUM_SEVERITY
  notifiers:
  - 40c72e28-283a-426a-ba56-e749c0847303
  - d8de3118-6f77-4a09-bed2-f8d86b732fd1
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Read-Only Root Filesystem
      booleanOperator: OR
      negate: false
      values:
      - value: 'false'
  scope:
  - cluster: 1bddd820-f647-466d-8b78-2506ad8140ed
  mitreAttackVectors: []
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
