kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: leaky-vessels-runc-container-breakout
spec:
  policyName: 'Leaky Vessels: runc container breakout'
  description: CVE-2024-21626 is a vulnerability in the runc container runtime allowing
    an attacker to break out of the container isolation and achieve full root RCE
    via a crafted image that exploits an issue within the WORKDIR instruction's handling.
  rationale: This vulnerability potentially allows an attacker to access host resources
    using a crafted file descriptor from the container, impacting both build and deployment
    operations.
  remediation: Remove Containerfile lines resembling 'WORKDIR /proc/self/fd/[ID]'
    (with ID being a system dependent file descriptor)
  categories:
  - Anomalous Activity
  - Kubernetes
  - Atipe
  disabled: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: ''
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: ^kube.*|^openshift.*|^redhat.*|^istio.*|^rhacs-operator.*|^stackrox.*
        label: null
    image: null
    expiration: null
  severity: HIGH_SEVERITY
  notifiers:
  - 40c72e28-283a-426a-ba56-e749c0847303
  - d8de3118-6f77-4a09-bed2-f8d86b732fd1
  policySections:
  - sectionName: Policy Section 1
    policyGroups:
    - fieldName: Dockerfile Line
      booleanOperator: OR
      negate: false
      values:
      - value: WORKDIR=.*\/proc\/self\/fd\/.*
  scope:
  - cluster: 1bddd820-f647-466d-8b78-2506ad8140ed
  mitreAttackVectors:
  - tactic: TA0004
    techniques:
    - T1611
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
