kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: polkit-in-image
spec:
  policyName: Polkit in Image
  description: Alert on deployments with Polkit present
  rationale: Leaving privileged administration tools like Polkit in an image potentially
    allows attackers to escalate privileges within the container.
  remediation: Use your package manager's "remove" command to remove polkit packages
    from the image build for production containers.
  categories:
  - Security Best Practices
  - Atipe
  disabled: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: ''
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: ^kube.*|^openshift.*|^redhat.*|^istio.*|^rhacs-operator.*|^stackrox.*
        label: null
    image: null
    expiration: null
  severity: LOW_SEVERITY
  notifiers:
  - 40c72e28-283a-426a-ba56-e749c0847303
  - d8de3118-6f77-4a09-bed2-f8d86b732fd1
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Image Component
      booleanOperator: OR
      negate: false
      values:
      - value: polkit=
      - value: policykit-1=
  scope:
  - cluster: 1bddd820-f647-466d-8b78-2506ad8140ed
  mitreAttackVectors: []
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
