kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: pwnkit:-cve-2021-4034---polkit-local-privilege-escalation-vulnerability
spec:
  policyName: 'PwnKit: CVE-2021-4034 - Polkit local privilege escalation vulnerability'
  description: Alert on deployments with images containing the PwnKit vulnerability
    (CVE-2021-4034). This is a local privilege escalation vulnerability impacting
    the pkexec binary.
  rationale: This vulnerability allows an unprivileged local attacker to escalate
    privileges, bypassing any authentication and policies due to incorrect handling
    of the process argument vector.
  remediation: Update the polkit package to 0.112-26.el7_9.1 (for RHEL 7-based container
    images) or polkit-0.115-13.el8_5.1 (for RHEL 8-based container images).
  categories:
  - Vulnerability Management
  - atipe
  disabled: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: ''
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: ^kube.*|^openshift.*|^redhat.*|^istio.*|^rhacs-operator.*|^stackrox.*
        label: null
    image: null
    expiration: null
  severity: CRITICAL_SEVERITY
  notifiers:
  - 6fba967b-b988-4a7e-a1c4-b324ece4408b
  - 086b31cd-ddb5-4d9a-879f-e92b05dd71a8
  - a9c588fe-ec1a-4f4e-b4e1-77d0a5f36750
  - bf93bf14-35c6-42b0-9645-935e0fb5f6bb
  policySections:
  - sectionName: CVE proibido
    policyGroups:
    - fieldName: CVE
      booleanOperator: OR
      negate: false
      values:
      - value: CVE-2021-4034
  scope:
  - cluster: 1bddd820-f647-466d-8b78-2506ad8140ed
    namespace: ''
    label: null
  mitreAttackVectors: []
  criteriaLocked: true
  mitreVectorsLocked: true
  isDefault: false
